// Role types and team definitions
export const Team = {
  GOOD: 'good',
  EVIL: 'evil',
};

export const RoleType = {
  TOWNSFOLK: 'townsfolk',
  OUTSIDER: 'outsider',
  MINION: 'minion',
  DEMON: 'demon',
  TRAVELLER: 'traveller',
  FABLED: 'fabled',
};

export const Phase = {
  SETUP: 'setup',
  FIRST_NIGHT: 'firstNight',
  NIGHT: 'night',
  DAY: 'day',
  NOMINATION: 'nomination',
  VOTING: 'voting',
  EXECUTION: 'execution',
  GAME_OVER: 'gameOver',
};

export const AbilityTiming = {
  PASSIVE: 'passive',
  FIRST_NIGHT: 'firstNight',
  EACH_NIGHT: 'eachNight',
  EACH_NIGHT_STAR: 'eachNightStar', // each night except first
  DAY: 'day',
  ON_DEATH: 'onDeath',
  ON_NOMINATION: 'onNomination',
  ON_EXECUTION: 'onExecution',
};

// Night action types
export const NightActionType = {
  CHOOSE_PLAYER: 'choosePlayer',
  CHOOSE_TWO_PLAYERS: 'chooseTwoPlayers',
  CHOOSE_YES_NO: 'chooseYesNo',
  RECEIVE_INFO: 'receiveInfo',
  CHOOSE_PLAYER_OR_PASS: 'choosePlayerOrPass',
};

// How many of each role type per player count
// [townsfolk, outsiders, minions, demons]
export const PLAYER_COUNT_DISTRIBUTION = {
  5:  [3, 0, 1, 1],
  6:  [3, 1, 1, 1],
  7:  [5, 0, 1, 1],
  8:  [5, 1, 1, 1],
  9:  [5, 2, 1, 1],
  10: [7, 0, 2, 1],
  11: [7, 1, 2, 1],
  12: [7, 2, 2, 1],
  13: [9, 0, 3, 1],
  14: [9, 1, 3, 1],
  15: [9, 2, 3, 1],
  16: [9, 3, 3, 1],
  17: [11, 2, 3, 1],
  18: [11, 3, 3, 1],
  19: [13, 2, 3, 1],
  20: [13, 3, 3, 1],
};

// ============================================================
// TROUBLE BREWING ROLES
// ============================================================

export const TROUBLE_BREWING_ROLES = {
  // --- TOWNSFOLK ---
  washerwoman: {
    id: 'washerwoman',
    name: 'Washerwoman',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing that 1 of 2 players is a particular Townsfolk.',
    firstNightOrder: 32,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'twoPlayersOneIs',
      targetType: RoleType.TOWNSFOLK,
    },
    reminders: ['Townsfolk', 'Wrong'],
  },
  librarian: {
    id: 'librarian',
    name: 'Librarian',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing that 1 of 2 players is a particular Outsider. (Or that zero are in play.)',
    firstNightOrder: 33,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'twoPlayersOneIs',
      targetType: RoleType.OUTSIDER,
    },
    reminders: ['Outsider', 'Wrong'],
  },
  investigator: {
    id: 'investigator',
    name: 'Investigator',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing that 1 of 2 players is a particular Minion.',
    firstNightOrder: 34,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'twoPlayersOneIs',
      targetType: RoleType.MINION,
    },
    reminders: ['Minion', 'Wrong'],
  },
  chef: {
    id: 'chef',
    name: 'Chef',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing how many pairs of evil players there are.',
    firstNightOrder: 35,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'evilPairCount',
    },
    reminders: [],
  },
  empath: {
    id: 'empath',
    name: 'Empath',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, you learn how many of your 2 alive neighbours are evil.',
    firstNightOrder: 36,
    otherNightOrder: 53,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'evilNeighborCount',
    },
    reminders: [],
  },
  fortune_teller: {
    id: 'fortune_teller',
    name: 'Fortune Teller',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, choose 2 players: you learn if either is a Demon. There is a good player that registers as a Demon to you.',
    firstNightOrder: 37,
    otherNightOrder: 54,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_TWO_PLAYERS,
      infoType: 'isDemon',
    },
    reminders: ['Red herring'],
  },
  undertaker: {
    id: 'undertaker',
    name: 'Undertaker',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, you learn which character died by execution today.',
    firstNightOrder: null,
    otherNightOrder: 52,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'executedRole',
    },
    reminders: ['Died today'],
  },
  monk: {
    id: 'monk',
    name: 'Monk',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, choose a player (not yourself): they are safe from the Demon tonight.',
    firstNightOrder: null,
    otherNightOrder: 12,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'protect',
      excludeSelf: true,
    },
    reminders: ['Protected'],
  },
  ravenkeeper: {
    id: 'ravenkeeper',
    name: 'Ravenkeeper',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'If you die at night, you are woken to choose a player: you learn their character.',
    firstNightOrder: null,
    otherNightOrder: 51,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      type: NightActionType.CHOOSE_PLAYER,
      infoType: 'playerRole',
    },
    reminders: [],
  },
  virgin: {
    id: 'virgin',
    name: 'Virgin',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'The 1st time you are nominated, if the nominator is a Townsfolk, they are executed immediately.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_NOMINATION,
    },
    reminders: ['No ability'],
  },
  slayer: {
    id: 'slayer',
    name: 'Slayer',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, during the day, publicly choose a player: if they are the Demon, they die.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.DAY,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'slay',
    },
    reminders: ['No ability'],
  },
  soldier: {
    id: 'soldier',
    name: 'Soldier',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You are safe from the Demon.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'demonSafe',
    },
    reminders: [],
  },
  mayor: {
    id: 'mayor',
    name: 'Mayor',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'If only 3 players live & no one is executed, your team wins. If you would die at night, another player might die instead.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'mayorBounce',
    },
    reminders: [],
  },

  // --- OUTSIDERS ---
  butler: {
    id: 'butler',
    name: 'Butler',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.',
    firstNightOrder: 38,
    otherNightOrder: 55,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'chooseMaster',
      excludeSelf: true,
    },
    reminders: ['Master'],
  },
  drunk: {
    id: 'drunk',
    name: 'Drunk',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: true,
    setupEffect: 'thinksTheyAreTownsfolk',
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'drunk',
    },
    reminders: ['Is the Drunk'],
  },
  recluse: {
    id: 'recluse',
    name: 'Recluse',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'You might register as evil & as a Minion or Demon, even if dead.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'registersAsEvil',
    },
    reminders: [],
  },
  saint: {
    id: 'saint',
    name: 'Saint',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'If you are executed, your team loses.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_EXECUTION,
      effect: 'evilWins',
    },
    reminders: [],
  },

  // --- MINIONS ---
  poisoner: {
    id: 'poisoner',
    name: 'Poisoner',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night, choose a player: they are poisoned tonight and tomorrow day.',
    firstNightOrder: 17,
    otherNightOrder: 7,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'poison',
    },
    reminders: ['Poisoned'],
  },
  spy: {
    id: 'spy',
    name: 'Spy',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.',
    firstNightOrder: 39,
    otherNightOrder: 56,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'grimoire',
    },
    reminders: [],
  },
  scarlet_woman: {
    id: 'scarlet_woman',
    name: 'Scarlet Woman',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'If there are 5 or more players alive & the Demon dies, you become the Demon. (Storyteller chooses which.)',
    firstNightOrder: null,
    otherNightOrder: 19,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'becomeDemon',
    },
    reminders: ['Is the Demon'],
  },
  baron: {
    id: 'baron',
    name: 'Baron',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'There are extra Outsiders in play. [+2 Outsiders]',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: true,
    setupEffect: 'addOutsiders',
    setupValue: 2,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
    },
    reminders: [],
  },

  // --- DEMON ---
  imp: {
    id: 'imp',
    name: 'Imp',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose a player: they die. If you kill yourself, a Minion becomes the Imp.',
    firstNightOrder: null,
    otherNightOrder: 24,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'kill',
      canTargetSelf: true,
    },
    reminders: ['Dead'],
  },
};

// ============================================================
// SECTS & VIOLETS ROLES
// ============================================================

export const SECTS_AND_VIOLETS_ROLES = {
  // --- TOWNSFOLK ---
  clockmaker: {
    id: 'clockmaker',
    name: 'Clockmaker',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing how many steps from the Demon to its nearest Minion.',
    firstNightOrder: 32,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'demonMinionDistance',
    },
    reminders: [],
  },
  dreamer: {
    id: 'dreamer',
    name: 'Dreamer',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, choose a player (not yourself): you learn 1 good and 1 evil character, 1 of which is correct.',
    firstNightOrder: 33,
    otherNightOrder: 52,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      infoType: 'oneGoodOneEvil',
      excludeSelf: true,
    },
    reminders: [],
  },
  snake_charmer: {
    id: 'snake_charmer',
    name: 'Snake Charmer',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, choose a player: if they are the Demon, you swap characters & alignments, then a good player becomes poisoned.',
    firstNightOrder: 20,
    otherNightOrder: 11,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'snakeCharm',
    },
    reminders: ['Poisoned'],
  },
  mathematician: {
    id: 'mathematician',
    name: 'Mathematician',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, you learn how many players\' abilities worked abnormally (due to another character) since dawn.',
    firstNightOrder: 40,
    otherNightOrder: 57,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'abnormalCount',
    },
    reminders: ['Abnormal'],
  },
  flowergirl: {
    id: 'flowergirl',
    name: 'Flowergirl',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, you learn if a Demon voted today.',
    firstNightOrder: null,
    otherNightOrder: 53,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'demonVoted',
    },
    reminders: ['Demon voted', 'Demon did not vote'],
  },
  town_crier: {
    id: 'town_crier',
    name: 'Town Crier',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, you learn if a Minion nominated today.',
    firstNightOrder: null,
    otherNightOrder: 54,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'minionNominated',
    },
    reminders: ['Minion nominated', 'Minion did not nominate'],
  },
  oracle: {
    id: 'oracle',
    name: 'Oracle',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, you learn how many dead players are evil.',
    firstNightOrder: null,
    otherNightOrder: 55,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'deadEvilCount',
    },
    reminders: [],
  },
  savant: {
    id: 'savant',
    name: 'Savant',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each day, you may visit the Storyteller to learn 2 things, 1 of which is true.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.DAY,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'twoStatementsOneTrue',
    },
    reminders: [],
  },
  seamstress: {
    id: 'seamstress',
    name: 'Seamstress',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.',
    firstNightOrder: 34,
    otherNightOrder: 51,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_TWO_PLAYERS,
      infoType: 'sameAlignment',
      oncePerGame: true,
      excludeSelf: true,
    },
    reminders: ['No ability'],
  },
  philosopher: {
    id: 'philosopher',
    name: 'Philosopher',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.',
    firstNightOrder: 2,
    otherNightOrder: 2,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'gainAbility',
      oncePerGame: true,
    },
    reminders: ['Is the Philosopher', 'Drunk'],
  },
  artist: {
    id: 'artist',
    name: 'Artist',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, during the day, privately ask the Storyteller any yes/no question.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.DAY,
      type: NightActionType.CHOOSE_YES_NO,
      oncePerGame: true,
    },
    reminders: ['No ability'],
  },
  juggler: {
    id: 'juggler',
    name: 'Juggler',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'On your 1st day, publicly guess up to 5 player\'s characters. That night, you learn how many you got correct.',
    firstNightOrder: null,
    otherNightOrder: 56,
    setup: false,
    nightAction: {
      timing: AbilityTiming.DAY,
      infoType: 'correctGuesses',
    },
    reminders: ['Correct'],
  },
  sage: {
    id: 'sage',
    name: 'Sage',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'If the Demon kills you, you learn that it is 1 of 2 players.',
    firstNightOrder: null,
    otherNightOrder: 42,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'demonIsOneOfTwo',
    },
    reminders: [],
  },

  // --- OUTSIDERS ---
  mutant: {
    id: 'mutant',
    name: 'Mutant',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'If you are "mad" about being an Outsider, you might be executed.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
    },
    reminders: [],
  },
  sweetheart: {
    id: 'sweetheart',
    name: 'Sweetheart',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'When you die, 1 player is poisoned from now on.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      effect: 'poisonOnDeath',
    },
    reminders: ['Poisoned'],
  },
  barber: {
    id: 'barber',
    name: 'Barber',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.',
    firstNightOrder: null,
    otherNightOrder: 41,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      effect: 'swapCharacters',
    },
    reminders: ['Haircuts tonight'],
  },
  klutz: {
    id: 'klutz',
    name: 'Klutz',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'When you learn that you died, publicly choose 1 alive player. If they are evil, your team loses.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      effect: 'klutzChoice',
    },
    reminders: [],
  },

  // --- MINIONS ---
  evil_twin: {
    id: 'evil_twin',
    name: 'Evil Twin',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'You & an opposing player know each other. If the good player is executed, evil wins. Good can\'t win if you are both alive.',
    firstNightOrder: 22,
    otherNightOrder: null,
    setup: true,
    setupEffect: 'twinPair',
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      infoType: 'twinReveal',
    },
    reminders: ['Twin', 'Is the Evil Twin'],
  },
  witch: {
    id: 'witch',
    name: 'Witch',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.',
    firstNightOrder: 23,
    otherNightOrder: 13,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'witchCurse',
    },
    reminders: ['Cursed'],
  },
  cerenovus: {
    id: 'cerenovus',
    name: 'Cerenovus',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night, choose a player & a good character: they are "mad" they are this character tomorrow, or might be executed.',
    firstNightOrder: 24,
    otherNightOrder: 14,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'madness',
    },
    reminders: ['Mad'],
  },
  pit_hag: {
    id: 'pit_hag',
    name: 'Pit-Hag',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night*, choose a player & a character they become (if not-in-play). If a Demon is created, deaths tonight are arbitrary.',
    firstNightOrder: null,
    otherNightOrder: 15,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'changeCharacter',
    },
    reminders: [],
  },

  // --- DEMONS ---
  fang_gu: {
    id: 'fang_gu',
    name: 'Fang Gu',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]',
    firstNightOrder: null,
    otherNightOrder: 28,
    setup: true,
    setupEffect: 'addOutsiders',
    setupValue: 1,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'fangGuKill',
    },
    reminders: ['Dead', 'Once'],
  },
  vigormortis: {
    id: 'vigormortis',
    name: 'Vigormortis',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbour. [-1 Outsider]',
    firstNightOrder: null,
    otherNightOrder: 29,
    setup: true,
    setupEffect: 'removeOutsiders',
    setupValue: 1,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'vigormortisKill',
    },
    reminders: ['Dead', 'Has ability', 'Poisoned'],
  },
  no_dashii: {
    id: 'no_dashii',
    name: 'No Dashii',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose a player: they die. Your 2 Townsfolk neighbours are poisoned.',
    firstNightOrder: null,
    otherNightOrder: 27,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'kill',
    },
    reminders: ['Dead', 'Poisoned'],
  },
  vortox: {
    id: 'vortox',
    name: 'Vortox',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no one is executed, evil wins.',
    firstNightOrder: null,
    otherNightOrder: 26,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'kill',
    },
    reminders: ['Dead'],
  },
};

// ============================================================
// BAD MOON RISING ROLES
// ============================================================

export const BAD_MOON_RISING_ROLES = {
  // --- TOWNSFOLK ---
  grandmother: {
    id: 'grandmother',
    name: 'Grandmother',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'You start knowing a good player & their character. If the Demon kills them, you die too.',
    firstNightOrder: 39,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.FIRST_NIGHT,
      type: NightActionType.RECEIVE_INFO,
      infoType: 'goodPlayerAndRole',
    },
    reminders: ['Grandchild'],
  },
  sailor: {
    id: 'sailor',
    name: 'Sailor',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, choose an alive player: either you or they are drunk until dusk. You can\'t die.',
    firstNightOrder: 10,
    otherNightOrder: 4,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'sailorDrunk',
    },
    reminders: ['Drunk'],
  },
  chambermaid: {
    id: 'chambermaid',
    name: 'Chambermaid',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.',
    firstNightOrder: 40,
    otherNightOrder: 58,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_TWO_PLAYERS,
      infoType: 'wokeCount',
      excludeSelf: true,
    },
    reminders: [],
  },
  exorcist: {
    id: 'exorcist',
    name: 'Exorcist',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are & doesn\'t wake tonight.',
    firstNightOrder: null,
    otherNightOrder: 20,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'exorcise',
    },
    reminders: ['Chosen'],
  },
  innkeeper: {
    id: 'innkeeper',
    name: 'Innkeeper',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, choose 2 players: they can\'t die tonight, but 1 is drunk until dusk.',
    firstNightOrder: null,
    otherNightOrder: 9,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_TWO_PLAYERS,
      effect: 'innkeeperProtect',
    },
    reminders: ['Protected', 'Drunk'],
  },
  gambler: {
    id: 'gambler',
    name: 'Gambler',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each night*, choose a player & guess their character: if you guess wrong, you die.',
    firstNightOrder: null,
    otherNightOrder: 3,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'gamble',
    },
    reminders: ['Dead'],
  },
  gossip: {
    id: 'gossip',
    name: 'Gossip',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Each day, you may make a public statement. Tonight, if it was true, a player dies.',
    firstNightOrder: null,
    otherNightOrder: 40,
    setup: false,
    nightAction: {
      timing: AbilityTiming.DAY,
      effect: 'gossipKill',
    },
    reminders: ['Dead'],
  },
  courtier: {
    id: 'courtier',
    name: 'Courtier',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.',
    firstNightOrder: 18,
    otherNightOrder: 8,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'courtierDrunk',
      oncePerGame: true,
    },
    reminders: ['Drunk 1', 'Drunk 2', 'Drunk 3', 'No ability'],
  },
  professor: {
    id: 'professor',
    name: 'Professor',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.',
    firstNightOrder: null,
    otherNightOrder: 43,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'resurrect',
      oncePerGame: true,
      targetDead: true,
    },
    reminders: ['No ability', 'Alive'],
  },
  minstrel: {
    id: 'minstrel',
    name: 'Minstrel',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_EXECUTION,
      effect: 'minstrelDrunk',
    },
    reminders: ['Everyone drunk'],
  },
  tea_lady: {
    id: 'tea_lady',
    name: 'Tea Lady',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'If both your alive neighbours are good, they can\'t die.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'protectGoodNeighbours',
    },
    reminders: ['Protected'],
  },
  pacifist: {
    id: 'pacifist',
    name: 'Pacifist',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'Executed good players might not die.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_EXECUTION,
      effect: 'pacifistSave',
    },
    reminders: [],
  },
  fool: {
    id: 'fool',
    name: 'Fool',
    type: RoleType.TOWNSFOLK,
    team: Team.GOOD,
    ability: 'The first time you die, you don\'t.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'foolProtection',
    },
    reminders: ['No ability'],
  },

  // --- OUTSIDERS ---
  tinker: {
    id: 'tinker',
    name: 'Tinker',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'You might die at any time.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
    },
    reminders: ['Dead'],
  },
  moonchild: {
    id: 'moonchild',
    name: 'Moonchild',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.',
    firstNightOrder: null,
    otherNightOrder: 49,
    setup: false,
    nightAction: {
      timing: AbilityTiming.ON_DEATH,
      effect: 'moonchildRevenge',
    },
    reminders: ['Dead'],
  },
  goon: {
    id: 'goon',
    name: 'Goon',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'goonDrunk',
    },
    reminders: ['Drunk'],
  },
  lunatic: {
    id: 'lunatic',
    name: 'Lunatic',
    type: RoleType.OUTSIDER,
    team: Team.GOOD,
    ability: 'You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.',
    firstNightOrder: 8,
    otherNightOrder: 5,
    setup: true,
    setupEffect: 'thinksTheyAreDemon',
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'lunaticChoice',
    },
    reminders: [],
  },

  // --- MINIONS ---
  godfather: {
    id: 'godfather',
    name: 'Godfather',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'You start knowing which Outsiders are in play. If 1 died today, choose a dead player tonight: they die. [-1 or +1 Outsider]',
    firstNightOrder: 19,
    otherNightOrder: 38,
    setup: true,
    setupEffect: 'modifyOutsiders',
    setupValue: 1,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'godfatherKill',
      targetDead: true,
    },
    reminders: ['Dead', 'Died today'],
  },
  devils_advocate: {
    id: 'devils_advocate',
    name: "Devil's Advocate",
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Each night, choose a living player (different to last night): if they are executed tomorrow, they don\'t die.',
    firstNightOrder: 20,
    otherNightOrder: 10,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'devilProtect',
    },
    reminders: ['Survives execution'],
  },
  assassin: {
    id: 'assassin',
    name: 'Assassin',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'Once per game, at night*, choose a player: they die, even if for some reason they could not.',
    firstNightOrder: null,
    otherNightOrder: 36,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'assassinate',
      oncePerGame: true,
    },
    reminders: ['Dead', 'No ability'],
  },
  mastermind: {
    id: 'mastermind',
    name: 'Mastermind',
    type: RoleType.MINION,
    team: Team.EVIL,
    ability: 'If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.',
    firstNightOrder: null,
    otherNightOrder: null,
    setup: false,
    nightAction: {
      timing: AbilityTiming.PASSIVE,
      effect: 'mastermindExtraDay',
    },
    reminders: [],
  },

  // --- DEMONS ---
  zombuul: {
    id: 'zombuul',
    name: 'Zombuul',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, if no one died today, choose a player: they die. The 1st time you die, you live but register as dead.',
    firstNightOrder: null,
    otherNightOrder: 25,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'zombuulKill',
    },
    reminders: ['Dead', 'Died today'],
  },
  pukka: {
    id: 'pukka',
    name: 'Pukka',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.',
    firstNightOrder: 27,
    otherNightOrder: 23,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT,
      type: NightActionType.CHOOSE_PLAYER,
      effect: 'pukkaPoison',
    },
    reminders: ['Poisoned', 'Dead'],
  },
  shabaloth: {
    id: 'shabaloth',
    name: 'Shabaloth',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.',
    firstNightOrder: null,
    otherNightOrder: 24,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_TWO_PLAYERS,
      effect: 'shabalothKill',
    },
    reminders: ['Dead', 'Alive'],
  },
  po: {
    id: 'po',
    name: 'Po',
    type: RoleType.DEMON,
    team: Team.EVIL,
    ability: 'Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.',
    firstNightOrder: null,
    otherNightOrder: 26,
    setup: false,
    nightAction: {
      timing: AbilityTiming.EACH_NIGHT_STAR,
      type: NightActionType.CHOOSE_PLAYER_OR_PASS,
      effect: 'poKill',
    },
    reminders: ['Dead', '3 attacks'],
  },
};

// ============================================================
// TRAVELLER ROLES
// ============================================================

export const TRAVELLER_ROLES = {
  scapegoat: {
    id: 'scapegoat',
    name: 'Scapegoat',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'If a player of your alignment is executed, you might be executed instead.',
    reminders: [],
  },
  gunslinger: {
    id: 'gunslinger',
    name: 'Gunslinger',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each day, after the 1st vote has been tallied, you may choose a player that voted: they die.',
    reminders: ['Dead'],
  },
  beggar: {
    id: 'beggar',
    name: 'Beggar',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'You must use the vote token of a dead player. If a player gives you theirs, you learn their alignment.',
    reminders: [],
  },
  bureaucrat: {
    id: 'bureaucrat',
    name: 'Bureaucrat',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow.',
    reminders: ['3 votes'],
  },
  thief: {
    id: 'thief',
    name: 'Thief',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each night, choose a player (not yourself): their vote counts negatively tomorrow.',
    reminders: ['Negative vote'],
  },
  apprentice: {
    id: 'apprentice',
    name: 'Apprentice',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'You are either the Townsfolk or the Minion your Storyteller chose for you.',
    reminders: ['Is the Apprentice'],
  },
  matron: {
    id: 'matron',
    name: 'Matron',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private.',
    reminders: [],
  },
  judge: {
    id: 'judge',
    name: 'Judge',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Once per game, if another player nominated, you may choose to force the current execution to pass or fail.',
    reminders: ['No ability'],
  },
  bishop: {
    id: 'bishop',
    name: 'Bishop',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Only the Storyteller can nominate. At least 1 opposing player is nominated per day.',
    reminders: [],
  },
  voudon: {
    id: 'voudon',
    name: 'Voudon',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Only you and the dead can vote. They don\'t need a vote token to do so. A 50% majority is not required.',
    reminders: [],
  },
  bone_collector: {
    id: 'bone_collector',
    name: 'Bone Collector',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Once per game, at night*, choose a dead player: they regain their ability until dusk.',
    reminders: ['No ability'],
  },
  barista: {
    id: 'barista',
    name: 'Barista',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each night, until dusk, 1) a player becomes sober, healthy & gets true info, or 2) their ability works twice.',
    reminders: ['Sober & Healthy', 'Acts twice'],
  },
  deviant: {
    id: 'deviant',
    name: 'Deviant',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'If you were funny today, you can\'t die by exile.',
    reminders: [],
  },
  harlot: {
    id: 'harlot',
    name: 'Harlot',
    type: RoleType.TRAVELLER,
    team: Team.GOOD,
    ability: 'Each night*, choose a living player: if they agree, you learn their character, but you both might die.',
    reminders: ['Dead'],
  },
};

// ============================================================
// FABLED ROLES
// ============================================================

export const FABLED_ROLES = {
  doomsayer: {
    id: 'doomsayer',
    name: 'Doomsayer',
    type: RoleType.FABLED,
    team: null,
    ability: 'If 4 or more players live, each living player may publicly choose (once per game) that a dead player becomes their alignment.',
    reminders: [],
  },
  angel: {
    id: 'angel',
    name: 'Angel',
    type: RoleType.FABLED,
    team: null,
    ability: 'Something bad might happen to whoever is most responsible for the death of a new player.',
    reminders: [],
  },
  buddhist: {
    id: 'buddhist',
    name: 'Buddhist',
    type: RoleType.FABLED,
    team: null,
    ability: 'For the first 2 minutes of each day, veteran players may not talk.',
    reminders: [],
  },
  hell_s_librarian: {
    id: 'hell_s_librarian',
    name: "Hell's Librarian",
    type: RoleType.FABLED,
    team: null,
    ability: 'Something bad might happen to whoever talks when the Storyteller has asked for silence.',
    reminders: [],
  },
  revolutionary: {
    id: 'revolutionary',
    name: 'Revolutionary',
    type: RoleType.FABLED,
    team: null,
    ability: '2 neighbouring players are known to be the same alignment. Once per game, one of them registers falsely.',
    reminders: [],
  },
  fiddler: {
    id: 'fiddler',
    name: 'Fiddler',
    type: RoleType.FABLED,
    team: null,
    ability: 'Once per game, the Demon secretly chooses an opposing player: all players vote for who of the 2 is to be executed.',
    reminders: [],
  },
  toymaker: {
    id: 'toymaker',
    name: 'Toymaker',
    type: RoleType.FABLED,
    team: null,
    ability: 'The Demon may choose not to attack. If they do this, they must do this again the following night.',
    reminders: [],
  },
  storm_catcher: {
    id: 'storm_catcher',
    name: 'Storm Catcher',
    type: RoleType.FABLED,
    team: null,
    ability: 'Name a good character. If in play, they can only die by execution, but evil players learn which player it is.',
    reminders: [],
  },
  fibbin: {
    id: 'fibbin',
    name: 'Fibbin',
    type: RoleType.FABLED,
    team: null,
    ability: 'Once per game, 1 good player might get false information.',
    reminders: ['Used'],
  },
  duchess: {
    id: 'duchess',
    name: 'Duchess',
    type: RoleType.FABLED,
    team: null,
    ability: 'Each day, 3 players may visit you to learn 1 of 2 things in private: your character or alignment (1 is false).',
    reminders: [],
  },
  sentinel: {
    id: 'sentinel',
    name: 'Sentinel',
    type: RoleType.FABLED,
    team: null,
    ability: 'There might be 1 extra or 1 fewer of an Outsider in play.',
    reminders: [],
  },
  spirit_of_ivory: {
    id: 'spirit_of_ivory',
    name: 'Spirit of Ivory',
    type: RoleType.FABLED,
    team: null,
    ability: 'There can\'t be more than 1 extra evil player.',
    reminders: ['No extra evil'],
  },
};

// ============================================================
// ALL ROLES COMBINED
// ============================================================

export const ALL_ROLES = {
  ...TROUBLE_BREWING_ROLES,
  ...SECTS_AND_VIOLETS_ROLES,
  ...BAD_MOON_RISING_ROLES,
  ...TRAVELLER_ROLES,
  ...FABLED_ROLES,
};

export function getRoleById(roleId) {
  return ALL_ROLES[roleId] || null;
}

export function getRolesByType(type) {
  return Object.values(ALL_ROLES).filter(r => r.type === type);
}

export function getRolesByTeam(team) {
  return Object.values(ALL_ROLES).filter(r => r.team === team);
}

export function getTeamForType(type) {
  switch (type) {
    case RoleType.TOWNSFOLK:
    case RoleType.OUTSIDER:
      return Team.GOOD;
    case RoleType.MINION:
    case RoleType.DEMON:
      return Team.EVIL;
    default:
      return null;
  }
}
